set "ORIG=%CD%"
set "SCRIPT_DIR=%~dp0"
cd "%SCRIPT_DIR%"
cmake -B build -DCMAKE_TOOLCHAIN_FILE=vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_PREFIX_PATH="%SCRIPT_DIR%jsoncpp\install;%SCRIPT_DIR%libjson-rpc-cpp\install"
cd "%ORIG%"
